/* Automatically generated by 'build-entry.js' */
import { Loading } from 'element-ui'

import CubeSelect from '../packages/cube-select/index.js'
import CubeSelectTree from '../packages/cube-select-tree/index.js'
import CubeSearchBar from '../packages/cube-search-bar/index.js'
import CubeCascader from '../packages/cube-cascader/index.js'
import CubeTable from '../packages/cube-table/index.js'
import CubeTableList from '../packages/cube-table-list/index.js'
import CubeTitle from '../packages/cube-title/index.js'
import CubeProgress from '../packages/cube-progress/index.js'

const components = [
  CubeSelect,
  CubeSelectTree,
  CubeSearchBar,
  CubeCascader,
  CubeTable,
  CubeTableList,
  CubeTitle,
  CubeProgress
]

const install = function (Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component)
  })
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
  window.Vue.use(Loading.directive)
}

/* Automatically export  */
export {
  install,
  CubeSelect,
  CubeSelectTree,
  CubeSearchBar,
  CubeCascader,
  CubeTable,
  CubeTableList,
  CubeTitle,
  CubeProgress
}

export default {
  version: '0.1.1-1',
  install,
  CubeSelect,
  CubeSelectTree,
  CubeSearchBar,
  CubeCascader,
  CubeTable,
  CubeTableList,
  CubeTitle,
  CubeProgress
}
