/* Automatically generated by 'build-entry.js' */
import { Loading } from 'element-ui';

import CubeSelect from './cube-select/index.js';
import CubeSelectTree from './cube-select-tree/index.js';
import CubeSearchBar from './cube-search-bar/index.js';
import CubeCascader from './cube-cascader/index.js';
import CubeTable from './cube-table/index.js';
import CubeTableList from './cube-table-list/index.js';
import CubeTitle from './cube-title/index.js';
import CubeProgress from './cube-progress/index.js';

const components = [
    CubeSelect,
  CubeSelectTree,
  CubeSearchBar,
  CubeCascader,
  CubeTable,
  CubeTableList,
  CubeTitle,
  CubeProgress
];

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
  Vue.use(Loading.directive);
}

export default {
  version: '0.1.0',
  install,
  CubeSelect,
  CubeSelectTree,
  CubeSearchBar,
  CubeCascader,
  CubeTable,
  CubeTableList,
  CubeTitle,
  CubeProgress
};
