/* Automatically generated by 'build-entry.js' */

import CubeTable from './cube-table/index.js';

const components = [
    CubeTable
];

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.1.0',
  install,
  CubeTable
};
